# Generated by Django 4.2.7 on 2024-02-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='main_category',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
