# Generated by Django 4.2.7 on 2024-02-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_categories_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='main_category',
            field=models.CharField(max_length=100),
        ),
    ]
