# Generated by Django 4.2.7 on 2024-02-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_categories_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='main_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
