# Generated by Django 4.2.7 on 2024-02-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_categories_main_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='maincategory',
        ),
    ]
