# Generated by Django 4.2.7 on 2024-02-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_maincategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maincategory',
        ),
    ]
